const allProducts = [
  {
    key: 1,
    name: "Whey Protein",
    flavour: "Brownie Chocolate",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 2,
    name: "Whey Protein",
    flavour: "Kesar Malai Kulfi",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 3,
    name: "Whey Protein",
    flavour: "Red Velvet",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 4,
    name: "Whey Protein",
    flavour: "Creamy Vennila",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 5,
    name: "Whey Protein",
    flavour: "Alphanso Mango",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 6,
    name: "Whey Protein",
    flavour: "Cookies And Cream",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 7,
    name: "Whey Protein",
    flavour: "Rhabri Kheer",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },
  {
    key: 8,
    name: "Whey Protein",
    flavour: "Rose Thandai",
    proteinGain_in_g: "26",
    eaa_in_g: "11.4",
    netWeight_in_kg: "2.27",
    lbs: "5",
    serving: "65",
  },

  //Protein Gainer

  {
    key: 9,
    flavour: "Brownie Chocolate",
    name: "Protein Gainer",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 10,
    name: "Whey Protein",
    flavour: "Kesar Malai Kulfi",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 11,
    name: "Whey Protein",
    flavour: "Red Velvet",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 12,
    name: "Whey Protein",
    flavour: "Creamy Vennila",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 13,
    name: "Whey Protein",
    flavour: "Alphanso Mango",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 14,
    name: "Whey Protein",
    flavour: "Cookies And Cream",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 15,
    name: "Whey Protein",
    flavour: "Rhabri Kheer",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
  {
    key: 16,
    name: "Whey Protein",
    flavour: "Rose Thandai",
    proteinGain_in_g: "26",
    bcaa_in_g: "5.5",
    netWeight_in_kg: "2.7",
    lbs: "6",
    serving: "77",
  },
];

export default allProducts;
